# Generated by Django 3.0.4 on 2020-04-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('request_from', 'request_to')},
        ),
    ]
