# Generated by Django 3.0.4 on 2020-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0002_auto_20200422_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
