# Generated by Django 3.0.4 on 2020-05-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0005_auto_20200425_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='begard_app.Plan'),
        ),
    ]
