# Generated by Django 3.0.4 on 2020-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0006_auto_20200506_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='begarduser',
            name='average_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='begarduser',
            name='username',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
