# Generated by Django 3.0.4 on 2020-05-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0007_auto_20200507_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begarduser',
            name='profile_img',
            field=models.ImageField(default='profiles/defaults/user-profile-image.jpg', null=True, upload_to='profiles'),
        ),
    ]
