# Generated by Django 3.0.4 on 2020-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begard_app', '0008_auto_20200513_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
